import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentPlayerFromRequest } from "@/lib/auth/get-session";
import { isAdmin } from "@/lib/auth/auth-service";
import { isTestMode } from "@/lib/test-mode/test-mode";
import { getConfig } from "@/lib/config";
import { resolveGroup } from "@/lib/groups/group-service";

/**
 * POST /api/[groupSlug]/admin/players
 * Create a new player in the group. Returns the player with invite token.
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ groupSlug: string }> }
) {
  const { groupSlug } = await params;

  // Auth check: either test mode, admin session, or admin secret
  const adminSecret = request.headers.get("x-admin-secret");
  const envAdminSecret = process.env.ADMIN_SECRET;

  let authorized = false;

  if (isTestMode()) {
    authorized = true;
  } else if (adminSecret && envAdminSecret && adminSecret === envAdminSecret) {
    // Bootstrap mode: use ADMIN_SECRET header for initial setup
    authorized = true;
  } else {
    const player = await getCurrentPlayerFromRequest(request, groupSlug);
    if (player && isAdmin(player.email)) {
      authorized = true;
    }
  }

  if (!authorized) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  const body = await request.json();
  const { name, email } = body;

  if (!name || !email) {
    return NextResponse.json(
      { error: "Name and email are required." },
      { status: 400 }
    );
  }

  // Resolve or create the group
  let group;
  try {
    group = await resolveGroup(groupSlug);
  } catch {
    // Group doesn't exist, create it
    group = await prisma.group.create({
      data: { slug: groupSlug, name: groupSlug },
    });
  }

  // Check if player already exists in this group
  const existing = await prisma.player.findUnique({
    where: { groupId_email: { groupId: group.id, email: email.toLowerCase() } },
  });

  if (existing) {
    return NextResponse.json(
      { error: "A player with this email already exists in this group." },
      { status: 409 }
    );
  }

  // Check max players
  const config = getConfig();
  const playerCount = await prisma.player.count({ where: { groupId: group.id } });
  if (playerCount >= config.maxPlayersPerGroup) {
    return NextResponse.json(
      { error: "This group has reached the maximum number of players." },
      { status: 400 }
    );
  }

  // Create the player (inviteToken is auto-generated by Prisma default)
  const player = await prisma.player.create({
    data: {
      groupId: group.id,
      name,
      email: email.toLowerCase(),
    },
  });

  return NextResponse.json({
    id: player.id,
    name: player.name,
    email: player.email,
    inviteToken: player.inviteToken,
  });
}

/**
 * GET /api/[groupSlug]/admin/players
 * List all players in the group.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ groupSlug: string }> }
) {
  const { groupSlug } = await params;

  // Auth check
  const adminSecret = request.headers.get("x-admin-secret");
  const envAdminSecret = process.env.ADMIN_SECRET;

  let authorized = false;

  if (isTestMode()) {
    authorized = true;
  } else if (adminSecret && envAdminSecret && adminSecret === envAdminSecret) {
    authorized = true;
  } else {
    const player = await getCurrentPlayerFromRequest(request, groupSlug);
    if (player && isAdmin(player.email)) {
      authorized = true;
    }
  }

  if (!authorized) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  let group;
  try {
    group = await resolveGroup(groupSlug);
  } catch {
    return NextResponse.json({ error: "Group not found" }, { status: 404 });
  }

  const players = await prisma.player.findMany({
    where: { groupId: group.id },
    orderBy: { createdAt: "asc" },
    select: {
      id: true,
      name: true,
      email: true,
      inviteToken: true,
      createdAt: true,
    },
  });

  return NextResponse.json({ players });
}
